### PR TITLE
Updated compile sources and run script to include new files

### PR DESCRIPTION
**Pull request by terryhorner**
Both HTTPCodes.h and Reachability.h need to be included in the build for the universal binary.

### CODE REVIEW

**Comment by claireyoung** [comment]
The diff looks good, but I just want to make sure I tested this properly. I opened the project and generated a Release build of KeenClientExample. Then, I took Build/Product/Relase-iphoneos/libKeenClient.a and dropped it into another separate app project (without Keen). In this separate project, I needed to add KeenClient.h, KeenProperties.h, and KIOEventStore.h to get the project to compile and run properly. Do we ask users to add HTTPCodes.h and Reachability.h just for convention? Since we do not ask them to add keen_io_sqlite3.h and keen_io_sqlite3ext.h.

**Comment by terryhorner** [comment]
Using the universal binary requires the header files that are included in `KeenClient.zip` (which is generated during the Build). `KeenClient-Cocoa.zip` is also generated for use in Mac apps.

You can find those zip files in `~/Users/{USERNAME}/Library/Developer/Xcode/DerivedData/KeenClient-{IDENTIFIER}/Build/Products/{CONFIGURATION}-iphonesimulator/` after running Build on the `KeenClient-Aggregate` target. We also post the most updated version [here](https://keen.io/docs/clients/iOS/usage-guide/#universal-binary) once we're ready to release.

I will generally unzip KeenClient.zip and just drag the resulting folder into a group in my Xcode project. Once you do that you can import `KeenClient.h` and you're all set.

**Comment by claireyoung** [comment]
Ok, I followed those steps and verified the 5 header files and libKeenClient-Aggregate.a were in the zip, dropped the contents of the KeenClient.zip folder into my project and it worked! :+1:

**Comment by heitortsergent** [comment]
Tested on iOS and Mac here too, both working from the zip. :shipit:

I had to import "Reachability.h" as well as "KeenClient.h". Creating an issue so we don't forget to update the README when we push the new version.

**Pull request merged**
