### PR TITLE
Delete Reachability files and add Podfile support

### LINKED ISSUE #97: Reachability in Podspec
Reachability is included as source files (Reachability.m and .h) in the podspec of KeenClient, however, Reachability is itself a Cocoapod which other pods such as AWSCore rely on. Attempting to use KeenClient with these pods will cause the build to fail, citing "duplicated symbols for architecture arm64."

### PR DESCRIPTION
**Pull request by heitortsergent**
**WIP**

This PR closes #97.

Removes the Reachability files from the project, and add them via CocoaPods.

Still getting an "Embedded dylibs/frameworks only run on iOS 8 or later" warning, need to fix that before merging.

### CODE REVIEW

**Comment by terryhorner** [comment]
What's up with Travis?

**Comment by heitortsergent** [comment]
It's complaining about the `use_frameworks!` option in the Podfile, probably because it has an outdated CocoaPods gem.

I'll finish the PR first, I might have to just take `use_frameworks!` out to get rid of the Xcode warning.

**Comment by terryhorner** [comment]
Besides Travis, :+1:

**Comment by heitortsergent** [comment]
Closing this for the moment, we're going the route of renaming Reachability to avoid duplicate issues.

We might get back to this if we can find a good way to make it easy to share the SDK via CocoaPods, and via a universal binary.

**Pull request closed without merging**
