### PR TITLE
Update Travis to use latest Xcode image, latest iOS version, and speed up build

### PR DESCRIPTION
**Pull request by baumatron**
- Update the Travis CI build to use the latest Xcode 8.3 image.
- Use the latest version of ruby included in the image. This way it doesn't need to be downloaded and that speeds up the build.
- Deploy using a simulator with the current version of iOS.
- Remove redundant and non-deterministic brew update and upgrade xctool commands that are currently just slowing down the build.
- Remove code coverage output that had been previously added for debugging purposes as coveralls seems to be giving reasonable results now.
- Remove unused simulator target parameters from xcodebuild build-only commands.

### CODE REVIEW

**Comment by masojus** [comment]
Cool. As I mentioned out-of-band, is it possible to run against a few SDKs in parallel like we do for other SDKs so we can test maybe the oldest SDK we reasonably expect to work as well as the latest and greatest? I imagine specifying a list of a few of [these](https://docs.travis-ci.com/user/osx-ci-environment/#Xcode-8.3) values for the `xcode_sdk` key would do the trick.

I'm not sure if we've ever tried running our stuff on tvOS or watchOS, or if there's reason to think it wouldn't work, but the docs claim those are options too.

**Comment by baumatron** [comment]
I'll look into that, though I've found those docs to have quite a few lies in them. Check out this build, for example: https://travis-ci.org/keenlabs/KeenClient-iOS/builds/225749844

**Comment by masojus** [comment]
Yeah I too have seen those docs to be more of a clue/treasure hunt as far as how one writes the `.travis.yml` rather than a guide. :S

**Comment by baumatron** [comment]
Turns out the docs weren't wrong, just the image: https://github.com/travis-ci/travis-ci/issues/7638#issuecomment-297527250. That's fixed, so we've got iOS 8.4, 9.3, and 10.3 validation now. I also added an OS X build because we're providing a pod for that platform.

In theory the build should be faster now because jobs run in parallel, but it seems scheduling jobs is actually the bottleneck. If this becomes a problem, we could consolidate the 3 iOS build-only jobs into a single job and specify the scheme as a custom environment variable.

I also just disabled building PR updates, since it's redundant. In the future there should just be a single Travis build per PR.

**Pull request merged**
