### PR TITLE
Add Carthage support.

### PR DESCRIPTION
**Pull request by zdavison**
We use Carthage @drop for iOS dependencies, so we added support for Keen.

### CODE REVIEW

**Comment by terryhorner** [comment]
Thanks for the PR @zdavison! We're not familiar with Carthage so give us some time to look it over and get back to this PR.

**Comment by zdavison** [comment]
Tweak it as you see fit, the only actual change is there's now a dynamic .framework target exposed in a scheme (Carthage just looks for schemes it can build and builds them, nothing more/less), which is nice to have anyways, the naming could be improved since I didn't want to conflict with your existing Keen schemes and targets.

**Comment by heitortsergent** [comment]
@zdavison taking a look at the PR over here :)

Just curious, is this necessary for Carthage or just for MGImageUtilities?

```objc
//! Project version number for MGImageUtilities.
FOUNDATION_EXPORT double KeenClientVersionNumber;

//! Project version string for MGImageUtilities.
FOUNDATION_EXPORT const unsigned char KeenClientVersionString[]; 
```

**Comment by zdavison** [comment]
Oh, that's left over from copy-paste. That is necessary to define a module (eg: @import) I believe.

**Comment by heitortsergent** [comment]
@zdavison thanks for the PR. I finally got around to adding Carthage support the SDK, it's working now starting from v3.5.2. 

I did it from scratch because I was reading about binaries/frameworks and Bitcode these past few weeks, it ended up looking really similar to your commits. I'd love if you guys could try it out and let us know if everything is working. :)

**Pull request closed without merging**
