### PR TITLE
Fix examples

### PR DESCRIPTION
**Pull request by heitortsergent**
This PR fixes the build errors in both examples project, caused by the test coverage addition.

It disables the `GCC_GENERATE_TEST_COVERAGE_FILES` and `GCC_INSTRUMENT_PROGRAM_FLOW_ARCS` that were, in turn, forcing the example apps to turn on those same flags to work (and would force all the users to turn these same flags in their apps).

It adds the flag `-enableCodeCoverage YES` to test script instead to generate code coverage data for use with Slather.

### CODE REVIEW

**Comment by terryhorner** [comment]
I'm still seeing the same build errors for some reason.

**Comment by heitortsergent** [comment]
@terryhorner could you please check two things:

- Make sure to clean the build folder before running the example projects again
- Double-check that the KeenClient target has the "Instrument Program Flow" and "Generate Legacy Test Coverage Files" flags set to `No`?

**Comment by terryhorner** [comment]
Thanks @heitortsergent. Everything was clean but the project build settings were overriding the example build settings even after deleting and re-cloning the repo. Weird.

Everything looks good to go now. :+1:

**Comment by heitortsergent** [comment]
_Xcode_ 

shrug

**Pull request merged**
